package com.upeu.modell;
// Generated 05/11/2018 04:31:58 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Persona persona;
     private String campo1;
     private String campo2;
     private String estado;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Persona persona) {
        this.idUsuario = idUsuario;
        this.persona = persona;
    }
    public Usuario(int idUsuario, Persona persona, String campo1, String campo2, String estado) {
       this.idUsuario = idUsuario;
       this.persona = persona;
       this.campo1 = campo1;
       this.campo2 = campo2;
       this.estado = estado;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCampo1() {
        return this.campo1;
    }
    
    public void setCampo1(String campo1) {
        this.campo1 = campo1;
    }
    public String getCampo2() {
        return this.campo2;
    }
    
    public void setCampo2(String campo2) {
        this.campo2 = campo2;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


